title: Ian Anderson - Transportation analytics expert
description: Self-taught analyst leveraging passion for transportation industry to achieve positive, data-driven outcomes for stakeholders.
show_downloads: false
google_analytics:
theme: jekyll-theme-tactile
