title: Transportation analytics expert
description: Self-taught analyst leveraging passion for transportation industry to achieve positive, data-driven outcomes for stakeholders.

Masters of Science in Business Analytics Candidate - Anticipated Summer 2022 Graduation. Raymond A. Mason School of Business at the College of William & Mary.
show_downloads: false
google_analytics:
theme: jekyll-theme-tactile
